name: Build
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: build
        run: |
          yarn install
          yarn build
      - name: Check version
        run: |
          cd build
          python_output=$(python ${GITHUB_WORKSPACE}/.github/check_version.py)
          echo "Python script output: $python_output"
          if [ -n "$python_output" ]; then
            echo "ERROR Version does not match in:"
            echo "$python_output"
            exit 1
          fi
